### ISSUE TITLE
The application will crash due to the diamond icon

### ISSUE THREAD

**Issue by rezamusic881** [iPoli/iPoli-android#106]
#### Project Information
* ###### Repository : https://github.com/iPoli/iPoli-android
* ###### Title App : myPoli
* ###### Publisher App : myPoli

***

#### Expected behavior
Supposedly, Application does not Crash, when click more than 1 time quickly On the "diamond icon" contained in Profiles.

#### Actual behavior
Previously I suspect the diamond icon, Because at the first time install the app and I tried clicking the diamond icon, then the application stopped. So I try to find fault until I find it. Problems when clicking more than 1 time quickly On the "diamond icon" contained in Profile causes "Crash".

#### How to reproduce
1. Instal App [here]( https://play.google.com/store/apps/details?id=io.ipoli.android)
2. Please login first.
3. When successfully Login, Log on "Profile".
4. In the "Profile" view you will find a diamond icon in the top corner.
5. Click on the diamond icon more than 1 time quickly.
6. The application will crash.

#### Environment
* ###### Device : Redmi Note 5A
* ###### System Operating : 7.1.0 Nougat
* ###### App Version : 2.1.5

***
***

#### <center>Recording Of The Issues</center>

https://youtu.be/xmL23Jy_0IM

***

#### Logcat
```
05-21 23:59:52.434  8510  8510 E AndroidRuntime: FATAL EXCEPTION: main
05-21 23:59:52.434  8510  8510 E AndroidRuntime: Process: io.ipoli.android, PID: 8510
05-21 23:59:52.434  8510  8510 E AndroidRuntime: org.solovyev.android.checkout.Check$AssertionException: Checkout is stopped
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at org.solovyev.android.checkout.Check.isFalse(Check.java:104)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at org.solovyev.android.checkout.Checkout.checkIsNotStopped(Checkout.java:255)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at org.solovyev.android.checkout.Checkout.makeInventory(Checkout.java:285)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at org.solovyev.android.checkout.Checkout.loadInventory(Checkout.java:268)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at io.ipoli.android.store.purchase.AndroidInAppPurchaseManager$loadAll$1.doResume(InAppPurchaseManager.kt:66)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6361)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
05-21 23:59:52.434  8510  8510 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

###### [Submit in github](http://www.github.com/rezamusic881)

**Comment by curiousily** [comment]
Fixed in the latest version! Thanks!
