### ISSUE TITLE
When turning on / off more than 1 click quickly on the "Google Calendars Sync" feature, the app crashes.

### ISSUE THREAD

**Issue by rezamusic881** [iPoli/iPoli-android#108]
#### Project Information
* ###### Repository : https://github.com/iPoli/iPoli-android
* ###### Title App : my Poli
* ###### Publisher App : my Poli

***

#### Expected behavior
Supposedly, when I want to enable the "Google Calendars Sync feature" and tap it more than once quickly, the app will not crash.

#### Actual behavior
Previously I was suspicious with this feature. because when I have not found this problem, when I access the feature it looks a bit slow. So I hunted down this problem and found the problem. when I want to enable the "Google Calendars Sync feature" and tap more than once quickly, the app crashes.

#### How to reproduce
1. Instal App [here](https://play.google.com/store/apps/details?id=io.ipoli.android)
2. Run the app.
3. Go to the "Settings" menu.
4. You'll find the "Google Calendars Sync" feature and click the feature quickly to enable / disable the feature, the app will crash.

#### Environment
* ###### Device : Redmi Note 5A
* ###### System Operating : 7.1.0 Nougat
* ###### App Version : 2.1.7

***
***

#### <center>Recording Of The Issues</center>
https://youtu.be/X8CvTjar0SE

***

#### Logcat
```
05-23 01:41:00.465 27577 27632 E AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-3
05-23 01:41:00.465 27577 27632 E AndroidRuntime: Process: io.ipoli.android, PID: 27577
05-23 01:41:00.465 27577 27632 E AndroidRuntime: java.lang.IllegalArgumentException: Key BuyPowerUpViewState is already added to the state?!
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at io.ipoli.android.common.redux.StateStore$CompositeReducer.reduce(StateStore.kt:192)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at io.ipoli.android.common.redux.StateStore.applyReducers(StateStore.kt:153)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at io.ipoli.android.common.redux.StateStore.access$applyReducers(StateStore.kt:106)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at io.ipoli.android.common.redux.StateStore$createStateActor$1.doResume(StateStore.kt:145)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1383)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:256)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1123)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1961)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1909)
05-23 01:41:00.465 27577 27632 E AndroidRuntime: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:128)
```

###### [Submit in github](http://www.github.com/rezamusic881)

**Comment by curiousily** [comment]
Fixed in the latest version. Thanks!
