### ISSUE TITLE
Does Google Calendar sync work?

### ISSUE THREAD

**Issue by Raltay** [iPoli/iPoli-android#57]
Hello,

How exactly does sync with Google Calendar work? In "Main Features", sync with Google calendar is listed, but I can't figure out how to make it work in Android App.

Thanks in advance :-)

**Comment by curiousily** [comment]
Hey @Raltay,

Thanks for the interest in the project :) Currently, we removed the sync with the calendar. It was too buggy and crashing the app more often than not.

We should have:

* Pick which calendars should be synced
* Read from/write to the calendar

etc.

Feel free to write back if you have an interest in helping out. I will leave this issue open until something is implemented.

Kind regards

**Comment by curiousily** [comment]
Hi @Raltay,

We've got Google Calendar sync up & running 😄

**Comment by 5pecia1** [comment]
Hi @curiousily 

I appended event through google calendar.
iPoli not add this event.
When do auto sync from google calendar?
And please make sync button.

Thank you.

**Comment by edwardqiu** [comment]
Having the same problem as @5pecia1

**Comment by curiousily** [comment]
Hi @5pecia1 and @edwardqiu,

Thank you for writing to us.

We are aware of the issues with the calendar sync. We use Android defined receiver which can be seen [here](https://github.com/iPoli/iPoli-android/blob/master/app/src/main/java/io/ipoli/android/app/receivers/AndroidCalendarEventChangedReceiver.java)

It uses standard way of listening for changes (so it should automatically sync):

```xml
        <receiver
            android:name=".app.receivers.AndroidCalendarEventChangedReceiver"
            android:priority="999">
            <intent-filter>
                <action android:name="android.intent.action.PROVIDER_CHANGED" />

                <data android:scheme="content" />
                <data android:host="com.android.calendar" />
            </intent-filter>
        </receiver>
```

However, [other users seem to have the same problem](https://stackoverflow.com/questions/20018619/listen-to-android-calendar-changes-sync-delete-insert-etc).

What devices are you using? Are you using the official Google Calendar app?

**Comment by edwardqiu** [comment]
I'm using the official Google Calendar app and my device is Samsung Galaxy S7 Edge (SM-G935F). The first time I synced with Google Calendar it imported all my events, but any changes I made to my calendars afterwards we're not synced. I tried creating a event on iPoli and it didn't sync over to Google Calendar

My other apps that sync with Google Calendar seem to work fine. For example, https://play.google.com/store/apps/details?id=prox.lab.calclock


Thanks for your time. I would love to continue using the app if calendar sync worked.

**Comment by 5pecia1** [comment]
Yes. 
I'm using the official Google Calendar app and my device is Samsung Galaxy Note 4(SM-N901S).
Other information is the same about iPoli as @edwardqiu.

Thank you.

**Comment by aliirezaaa** [comment]
Hi 
thanks for your really good calendar.
i have same problem. but i understand when phone connect to internet , sync not working . but when phone is offline sync calendar works fine.
i tested it on Genymotion android 4.2.2 and 7.0 with official google calendar 
hope it help you 
thanks

**Comment by edwardqiu** [comment]
@curiousily 

Update: Google Calendar sync to iPoli is working for me now, but sync from iPoli to Google Calendar is not working.

**Comment by curiousily** [comment]
We're working on version 2.0 in the current master branch. Will revisit when those features are reimplemented. Thanks!
