### ISSUE TITLE
Export to Calendar

### ISSUE THREAD

**Issue by CorentinLemaitre** [iPoli/iPoli-android#77]
Hello, 
Your app is really awsome! i am fast ready to use your solution!
I have seen that there is the calendar import.

The more usefull for me is the calendar export to share on the correct calendar the project you are working on. It is a good way to access your planning on a computer for exemple.

Hope it is possible. 

Best regards, Corentin

**Comment by lextiz** [comment]
Hi @curiousily, thanks for a good app. Is it planned to have this feature (sync from iPoli to google calendar) in 2.0? Such feature is game changer for me.
