### ISSUE TITLE
Repeating quests can't be deleted

### ISSUE THREAD

**Issue by obulat** [iPoli/iPoli-android#83]
When deleting a quest from the Repeating Quests page, the app doesn't delete the quest itself but simply deletes the scheduling information.
I can't find a way to fully delete repeating quests.

**Comment by curiousily** [comment]
Hey, @obulat,

I've been trying to reproduce this and really couldn't do it. Are the repeating quests created by you or created from a Challenge? We can discuss this further via our Slack community channel. Shoot me an email at venelin@ipoli.io to invite you there and try to figure this one out.

Thanks!

**Comment by obulat** [comment]
I created a repeating quest just to test it, and called it '1'. Now, on the repeating quest screen I click on the 'three dots' icon, and two options appear: Edit and Delete. I click on 'Delete', but nothing happens. It stays on the repeating quests screen with 'Unscheduled for 10 minutes or less' underneath it.

**Comment by curiousily** [comment]
We're working on version 2.0 in the current master branch. Will revisit when those features are reimplemented. Thanks!
